name: Clone Public Repository Workflow

on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  
jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone JohnFounds7/clone_me PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'JohnFounds7'
          repository: 'clone_me'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd clone_me
          ls -la
          
  publish:
    runs-on: ubuntu-latest
    steps:  

    - name: Cloning repo
      uses: actions/checkout@v2

    - name: Publish to Sharepoint
      uses: obrassard/action-sharepoint-publish@v1.0.1
      with:
       site_url: 'https://avivesolutions.sharepoint.com'
       library_folder: 'Documents/Departments/R&D/Firmware/Johns Work'
       sharepoint_user: 'jfounds@avive.life'
       sharepoint_password: '4488Sp@rus'
